### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by richardfugisse** [luisfontes19/redmine_stats#2]
The redmine return the message:

Page not found

The page you were trying to access doesn't exist or has been removed.

Back

**Comment by luisfontes19** [comment]
Can you give me more information about the error?

The message, is displayed when you access redmine? or the Statistics menu?
Which Redmine version are you using?
Can you post here the error in the log?

**Comment by dominch** [comment]
I have same issue, it's: The action 'current_week' could not be found for StatsController 
and it works when "current_week" is stripped from url (side column links are not working" 
changing current_week to foo causes same error (foo action count not be found for Stats controller) 
seems that it's some routing problem, time_filter is not parsed

**Comment by dominch** [comment]
I found issue in another plugin (redcase), there was catch-all routing line, after removing that one: 
match ':controller(/:action(/:id))(.:format)'
it worked on this plugin. Hope that will help somebody else (Richard too?)

**Comment by matbott** [comment]
I have the same problem when I select "since Beginning of time".
Redmine Version 2.5.1

**Comment by luisfontes19** [comment]
Did you tried dominch's fix? (In config/routes.rb remove the line starting with match)

**Comment by libooo** [comment]
i have the same problem. here is the logs:

>Started GET "/" for 127.0.0.1 at 2015-02-05 18:04:02 +0800
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
  Rendered welcome/index.html.erb within layouts/base (3.1ms)
Completed 200 OK in 14.1ms (Views: 7.0ms | ActiveRecord: 4.0ms)
Started GET "/stats/current_week" for 127.0.0.1 at 2015-02-05 18:04:04 +0800
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: admin (id=1)
Completed 404 Not Found in 5.0ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
  app/models/project.rb:289:in `find'


Started GET "/stats/current_month?project=all_projects" for 127.0.0.1 at 2015-02-05 18:04:11 +0800
Processing by StatsController#index as HTML
  Parameters: {"project"=>"all_projects", "time_filter"=>"current_month"}
  Current user: admin (id=1)
Completed 404 Not Found in 5.5ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
  app/models/project.rb:289:in `find'


Started GET "/stats/current_month?project=all_projects" for 127.0.0.1 at 2015-02-05 18:04:14 +0800
Processing by StatsController#index as HTML
  Parameters: {"project"=>"all_projects", "time_filter"=>"current_month"}
  Current user: admin (id=1)
Completed 404 Not Found in 4.4ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
>  app/models/project.rb:289:in `find'

**Comment by luisfontes19** [comment]
libooo I think your problem is different from dominch's
Anyway, I've tried to fix both in [commit 6a34a980cd](https://github.com/luisfontes19/redmine_stats/commit/6a34a980cdb2892e64253d5adb5b3adcdeec166b)

Can you guys give me some feedback to know if it worked?
Also, I've updated the README with the minimum version requirements, your problems could be related to this...

**Comment by aalmada** [comment]
I have the latest versions (cd202d7a9cb9dea6f79c096537cafb28470e7199) but still experience the 'current_week' issue reported by dominch

Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p594 (2014-10-27) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.11
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  redcase                        1.0 beta 2.0
  redmine_bootstrap_kit          0.1
  redmine_jenkins                0.1
  redmine_stats                  0.0.2

**Comment by dominch** [comment]
There is issue in redcase, that is old plugin written in protoype and not compatiblem with jquery (used in newer versions of redmine).
Try to remove redcase - restart redmine and links should work. 
Have You changed redcase routing file? It's in conflict with many other plugins.

**Comment by aalmada** [comment]
Sorry to be polluting this issue with issues from some other plugin.
I would like to keep Redcase.
I didn't try you suggested fix as I don't have Ruby experience and unfortunately I can't figure out where the change as to be made.
I noticed there was a commit for Redcase a few hours ago. I tried it but still have the same behavior. I'll try to get feedback from there, now that someone is taking a look at it.
Thanks!

**Comment by dominch** [comment]
It's still using protoype which cause many jquery errors :( 
That commit should fix Your problem with routing. 
Still You can easily find out if redcase coflicts with routing of this plugin, just move redcase from plugins to tmp directory, restart and try 404 link. Then You can move it again to plugins, restart and still have it.

**Comment by aalmada** [comment]
I temporarly removed Redcase as you suggested and now redmine_stats works fine.
Thanks for the help. I just hope they fix Redcase.

**Comment by dominch** [comment]
check out plugins/redcase/config.yml
if last line is: 
<pre>
match ':controller(/:action(/:id))(.:format)' 
</pre>
then You have conflicting version 
change it to: 
<pre>
match ':controller(/:action(/:id))(.:format)', controller: /redcase/
</pre>
That works on my side with this plugin. I will update redcase soon, there were some changes in routing that should help.

**Comment by aalmada** [comment]
In the version I have config.yml has been renamed to routes.rb
I made the changes you suggested and both plugins now work.
Thanks a lot for taking the time to help me!

**Comment by dominch** [comment]
My mistake, it should be routes.rb as You wrote :) 
If You have this line - then You don't have newest redcase, best version is 1.0-RC from bugzinga, You probably have old trunk.

**Comment by darshit1990** [comment]
hey..!! I have Redmine 2.6.1-2 and I have the same problem of Page not Found. and also I got the error of label like Translation missing can u help me out for this.. your plugin seems very helpful to me
![stats 2](https://cloud.githubusercontent.com/assets/11157216/6325563/fc1629ae-bb6e-11e4-86cf-8724fd894d50.png)
![stats](https://cloud.githubusercontent.com/assets/11157216/6325564/fc167f94-bb6e-11e4-9c36-7959c3b67edf.png)

.

**Comment by luisfontes19** [comment]
Hello, if you replace in the url "current_week" by "last_week" for example, it does work right?
The label problem is weird. Do you have any error in the logs?

**Comment by darshit1990** [comment]
Hi, I have installed Redmine 2.3.2 and re-installed your plugin. but still I face the same issue . Even though I have changed the URL the same message is displayed. And ya the label issue still continued. I have checked the log file but it seems pretty okay.

**Comment by dominch** [comment]
luis: maybe it's wise to put better constrains to this plugin so any other will not take over that routing. Simple example is redcase - it brake this plugin for sure, but not other plugins so people are confused.

**Comment by j0ty** [comment]
Hi, have not found error. 
Version redmine-2.6.1, plugins: Issue Importer 1.2.2, Due Date Reminder plugin 0.4

Log:
Started GET "/stats/current_week" for 127.0.0.1 at 2015-04-20 18:10:25 +0300
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: admin (id=1)
Completed 404 Not Found in 15.6ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
  app/models/project.rb:289:in `find'

**Comment by yokatan** [comment]
I have the same error

Version redmine-2.6.1
ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
app/models/project.rb:289:in `find'

any solution?

**Comment by steexx** [comment]
The same error.

Redmine version                2.6.5.stable
commit 4dee273c9a78e32c821ed9ec03b28f97df57e354

Started GET "/stats/current_week" for ***
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: ***
Completed 404 Not Found in 12.9ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
  app/models/project.rb:289:in `find'

**Comment by luisfontes19** [comment]
Hello,
First of all forgive me for my late response, but I haven't got much time to work on this project...

From the logs you gave me I cannot be sure of where the bug occurs, but I've changed some things in the code trying to fix it, so please test the new version, and if does not work, give me a more detailed error log please

**Comment by archsh** [comment]
Hello
I got the same issue, but it was working this morning, don't know why.

I got the following logs:

Started GET "/global_stats/current_week" for 119.253.38.50 at 2015-07-01 16:12:16 +0800
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: shenmc (id=4)
Completed 404 Not Found in 28.7ms

ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
  app/models/project.rb:289:in `find'

**Comment by steexx** [comment]
May be this trace could help you: 

Redmine. Error 404

Global_error
Couldn't find Project without an ID 

Back  

Error log

        /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation/finder_methods.rb:313:in `find_with_ids'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation/finder_methods.rb:107:in `find'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/querying.rb:5:in `find'
/srv/redmine/2.6-stable/app/models/project.rb:289:in `find'
/srv/redmine/2.6-stable/plugins/redmine_stats/app/models/stat.rb:64:in `block in authors'
/srv/redmine/2.6-stable/plugins/redmine_stats/app/models/stat.rb:63:in `each'
/srv/redmine/2.6-stable/plugins/redmine_stats/app/models/stat.rb:63:in `authors'
/srv/redmine/2.6-stable/plugins/redmine_stats/app/controllers/stats_controller.rb:22:in `index'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:491:in `_run__2260602403663271994__process_action__1767665779097272869__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
/var/lib/gems/1.9.1/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/var/lib/gems/1.9.1/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__143956689429218958__call__3847284055124688206__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:580:in `process_client'
/usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:660:in `worker_loop'
/usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:527:in `spawn_missing_workers'
/usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:538:in `maintain_worker_count'
/usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:303:in `join'
/usr/bin/unicorn:126:in `<main>'

**Comment by Ben1024** [comment]
steexx, I met the same issue. How do you get the error log?

**Comment by steexx** [comment]
Ben1024, by this plugin: https://www.redmine.org/plugins/usability

**Comment by Ben1024** [comment]
steexx, does this plugin work well on your system now?

**Comment by ElskerDane** [comment]
Unfortunately, I am having the same error as everyone else seems to be having:
![capture](https://cloud.githubusercontent.com/assets/12851016/9640674/a2b09522-5180-11e5-935d-b02978cc7991.PNG)

**Comment by fpvolquind** [comment]
Hi!
I tested the plugin with a fresh redmine (2.5.3) installation, and got the same issue as steexx. The page stops working whenever I add a single task to the single project I have set up.

The error happens when the plugin tries to get the list of projects when there is none selected, or the list of the users when a project is selected on lines 62-75 of \redmine_stats\app\models\stat.rb. Replacing 'Project.find' with 'Project.find_by_id' (same with 'User.find' -> 'User.find_by_id') solves this issue, but I get other errors after.

Is there a certain version of rails, or some project setting required for the plugin to work? Maybe this is a database-related problem?
Here is my environment:
Environment:
  Redmine version                2.5.3.stable
  Ruby version                   2.1.6-p336 (2015-04-13) [x64-mingw32]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.5
  extra_queries                  2.0.0
  redmine_knowledgebase          3.0.7
  redmine_ldap_sync              2.0.7.devel
  redmine_stats                  0.0.3
  usability                      1.3.0

**Comment by myaspm** [comment]
*Couldnt find Project with id : * is definitely a problem with redmines using postgreSQL. I somehow managed to get into the plugins home page by some tweaks in the code but even then paths break, you can't open individual projects and so on.

Debugging so far i got this : Trying to access ActiveRecord::Relation objects by row.id, row.name etc. crashes the plugin ONLY IF you use PostgreSQL. I tested with many versions of redmine and with many other sql types and versions and only one that gives this exception is postgreSQL environment.

Trying to fix this all the way is such a drag, i couldn't manage to do it since the start of the month. I'll give it a break for now but if i could fix it, i'll post a pull request and notify you people.
